kind: Pod
apiVersion: v1
metadata:
  name: nginx2
spec:
  containers:
    - name: mybackend
      image: nginx
      volumeMounts:
      - mountPath: "/mnt/azure"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk